"""actual_db

Revision ID: bd5e0e21f859
Revises: 335586c9b239
Create Date: 2023-05-24 20:56:05.556859+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bd5e0e21f859'
down_revision = '335586c9b239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis', sa.Column('doctor_diagnosis', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnosis', 'doctor_diagnosis')
    # ### end Alembic commands ###
